global RCS_ALTERNATE_DEADZONE is {
	parameter TRANSLATION.
	parameter DEADZONE is 0.01.
	
	if ABS(TRANSLATION:X) < 0.153 and ABS(TRANSLATION:X) > DEADZONE {
		set TRANSLATION:X to 0.153.
	}
	if ABS(TRANSLATION:Y) < 0.153 and ABS(TRANSLATION:Y) > DEADZONE {
		set TRANSLATION:Y to 0.153.
	}
	if ABS(TRANSLATION:Z) < 0.153 and ABS(TRANSLATION:Z) > DEADZONE {
		set TRANSLATION:Z to 0.153.
	}
	
	return TRANSLATION.
}.